export default [
    "Alfa Romeo Giulia",
    "Audi A6 C7",
    "Audi Q7",
    "Audi Q8",
    "Audi R8 '20",
    "Audi RS5 F5",
    "Audi RS6 Avant",
    "Audi RS6 C5",
    "Audi RS7 4G",
    "Audi RS7 8С",
    "Audi S3 8V",
    "Audi TT-RS",
    "Bentley Bentayga",
    "Bentley Continental GT Convertible",
    "BMW 535i E34",
    "BMW I8",
    "BMW 750Li E38",
    "BMW 750Li G12",
    "BMW M2 F22",
    "BMW M3 E30",
    "BMW M3 E36",
    "BMW M5 E39",
    "BMW 850csi",
    "BMW M4 Competition G82",
    "BMW M4 F82",
    "BMW M5 CS",
    "BMW M5 Competition",
    "BMW M5 Competition LCI",
    "BMW M5 E60",
    "BMW M8 F92",
    "BMW X5 E53",
    "BMW X5 G05 '19",
    "BMW X5M E70",
    "BMW X6M F96",
    "BMW X7 G07",
    "Bugatti Bolide",
    "Bugatti Chiron",
    "Bugatti Divo",
    "Bugatti Bolide",
    "Cadillac CTS-V '16",
    "Cadillac Escalade",
    "Chevrolet Camaro 2012",
    "Chevrolet Camaro ZL1 Hennessey",
    "Chevrolet Chevelle SS",
    "Chevrolet Corvette C8",
    "Chevrolet Tahoe",
    "Chevrolet Impala 1967",
    "Cadillac Superior Hearse ECTO-1",
    "Dodge Challenger HEMI",
    "Dodge Charger '16",
    "Dodge Charger R/T '69",
    "Dodge Viper 1999",
    "Dodge Ram 1500 TRX",
    "Ferrari F812 Superfast",
    "Ferrari FF",
    "Ferrari LaFerrari",
    "Ferrari Portofino",
    "Ferrari SF90",
    "Ford F-150 Raptor",
    "Ford Mustang GT `18",
    "Ford Mustang Hoonicorn 1965",
    "Honda Civic EK",
    "Jaguar F-Type",
    "Jaguar XF-R",
    "Jeep 4x4",
    "Jeep Grand Cherokee SRT-8",
    "Kia Stinger",
    "Koenigsegg Agera RS",
    "Lamborghini Aventador SVJ",
    "Lamborghini Diablo",
    "Lamborghini Huracan",
    "Lamborghini Sian",
    "Lamborghini Urus",
    "Lexus LX570 WALD",
    "Lexus RC-F",
    "Lincoln Continental",
    "Land-Rover Defender 2020",
    "Lada Vesta",
    "Lada Priora",
    "Maserati GranTurismo S",
    "Mazda RX7",
    "Mazda RX7 Veilside",
    "McLaren P1",
    "Mercedes-Benz 300sl",
    "Mercedes-AMG ONE",
    "Mercedes-Benz C63 AMG W204",
    "Mercedes-Benz C63 Coupe (цешка)",
    "Mercedes-Benz CLS63 AMG",
    "Mercedes-Benz E55 AMG W210",
    "Mercedes-Benz E63s W213 ",
    "Mercedes-Benz E63s W213 Rest",
    "Mercedes-Benz EQG",
    "Mercedes-Benz G500 4x4",
    "Mercedes-Benz G63 AMG 6x6",
    "Mercedes-Benz G63 AMG W464 (новый гелик)",
    "Mercedes-Benz G65 AMG W463 (олдовый гелик)",
    "Mercedes-Benz GLE53 AMG",
    "Mercedes-Benz GLS63 AMG",
    "Mercedes-Benz GT63s AMG 4-Door (акула)",
    "Mercedes-Benz GTR AMG C190",
    "Mercedes-Benz Pullman",
    "Mercedes-Benz S500 W223",
    "Mercedes-Benz S600 W140 (кабан)",
    "Mercedes-Benz S63 AMG Coupe W222",
    "Mercedes-Benz S63 AMG W222",
    "Mercedes-Benz S63 W221",
    "Mercedes-Benz Vision AVTR",
    "Mercedes-Benz V-Class",
    "Mercedes-Maybach S650",
    "Mercedes-Benz 300 CE 6.0 (волчок)",
    "Mini Cooper Works GP",
    "Mitsubishi Lancer Evolution IX",
    "Mitsubishi Lancer Evolution X",
    "Nissan 350Z",
    "Nissan GT-R R35",
    "Nissan GT-R R50",
    "Nissan Silvia S15",
    "Nissan Skyline GT-R R34",
    "Nissan Titan",
    "Porsche 911",
    "Porsche 718 Cayman GT4",
    "Porsche Cayenne Turbo",
    "Porsche Panamera Turbo",
    "Porsche Taycan Turbo S",
    "Porsche 911 '93",
    "Porsche 918 Spyder",
    "Range Rover SVR",
    "Range Rover Vogue",
    "Rolls-Royce Cullinan",
    "Rolls-Royce Phantom",
    "Rolls-Royce Wraith",
    "Rolls-Royce Ghost",
    "Shelby Mustang GT500",
    "Skoda Octavia RS A7",
    "Subaru Impreza WRX STI ",
    "Subaru WRX STi 2005",
    "Subaru WRX  STi",
    "Tesla Cybertruck",
    "Tesla Model S P90D",
    "Tesla Model X P90D",
    "Toyota AE86",
    "Toyota Camry XV40",
    "Toyota Camry XV55",
    "Toyota Camry XV70",
    "Toyota Land Cruiser 200",
    "Toyota Mark 100",
    "Toyota Supra A80",
    "Toyota Supra A90",
    "Volga",
    "Volvo XC90",
    "УАЗ 3151",
    "Quadra Turbo-R V-Tech"
]