export default [
  "Akuma",
  "Avarus",
  "Bagger",
  "Bati 801",
  "Bati 801RR",
  "BF400",
  "BMW S 1000 RR",
  "BMX (Вело)",
  "Carbon RS",
  "Chimera",
  "Cliffhanger",
  "Cruiser (Вело)",
  "Daemon",
  "Deamon",
  "Defiler",
  "Diabolus",
  "Double-T",
  "Ducati Superleggera",
  "Endurex (Вело)",
  "Enduro",
  "Esskey",
  "Faggio",
  "Faggio гоночный",
  "Faggio заказной",
  "FCR 1000",
  "FCR 1000 заказной",
  "Fixter (Вело)",
  "Gargoyle",
  "Hakuchou",
  "Hakuchou Drag",
  "Harley-Davidson Sportster Iron 883",
  "Hexer",
  "Innovation",
  "Innovation",
  "Kawasaki Z1000",
  "Kawasaki Z800",
  "KTM 690 DUKE",
  "Lectro",
  "Manchez",
  "Ninja H2",
  "Nemesis",
  "Nightblade",
  "PCJ 600",
  "Rat Bike",
  "Ruffian",
  "Sanchez",
  "Sanctus",
  "Scorcher (Вело)",
  "Shotaro",
  "Sovereign",
  "Thrust",
  "Tri-Cycles (Вело)",
  "Vader",
  "Vindicator",
  "Vortex",
  "Wheppet (Вело)",
  "Wolfsbane",
  "Yamaha YZF-R1",
  "Zombie Babber"
]
