export default [
  "811",
  "8F Drafter",
  "9F",
  "9F Cabrio",
  "Adder",
  "Alpha",
  "Asbo",
  "Asea",
  "Asterope",
  "Autarch",
  "Baller",
  "Baller",
  "Baller LE",
  "Banshee",
  "Banshee 900R",
  "BeeJay XL",
  "Bestia GTS",
  "Bison",
  "Blade",
  "Blista",
  "Blista Compact",
  "Blista Kanjo",
  "Bobcat XL",
  "Bodhi",
  "Brawler",
  "BRIOSO R/A",
  "Buccaneer",
  "Buccaneer заказной",
  "Bufallo",
  "Bufallo S",
  "Bullet",
  "Burger Shot Stallion",
  "Benson",
  "Burrito",
  "Caracara 4x4",
  "Carbonizzare",
  "Casco",
  "Cavalcade",
  "Cheburek",
  "Cheetah",
  "Cheetah Classic",
  "Chino",
  "Chino заказной",
  "Clique",
  "Cognoscenti",
  "Cognoscenti 55",
  "Comet",
  "Comet Retro заказной",
  "Congnoscenti Cabrio",
  "Contender",
  "Coquette",
  "Coquette BlackFin",
  "Coquette Classic",
  "Cyclone",
  "Deviant",
  "Dilettante",
  "Dominator",
  "Dominator",
  "Dominator GTX",
  "Drift Tampa",
  "Drift Yosemite",
  "Dubsta",
  "Dubsta",
  "Dubsta 6x6",
  "Dukes",
  "Duneloader",
  "Dynasty",
  "Elegy Retro заказной",
  "Elegy RH8",
  "Emerus",
  "Emperor",
  "Emperor",
  "Entity XF",
  "ETR1",
  "Everon",
  "Exemplar",
  "F620",
  "Faction",
  "Faction заказной",
  "Faction Donk заказной",
  "Felon",
  "Felon GT",
  "Feltzer",
  "FMJ",
  "FQ 2",
  "Freecrawler",
  "Fugitive",
  "Furia",
  "Furore GT",
  "Fusilade",
  "Futo",
  "Gauntlet",
  "Gauntlet",
  "Gauntlet Hellfire",
  "Glendale",
  "GP1",
  "Granger",
  "Gresley",
  "GT500",
  "Guardian",
  "Gang Burrito",
  "Habanero",
  "Hellion",
  "Hermes",
  "Hotknife",
  "Hotring Sabre",
  "Huntley S",
  "Imorgon",
  "Impaler",
  "Infernus",
  "Infernus Classic",
  "Ingot",
  "Intruder",
  "Issi",
  "Itali GTB",
  "Itali GTB заказной",
  "Itali GTO",
  "Jackal",
  "JB 700W",
  "Jester",
  "Jugular",
  "Kalahari",
  "Khamelion",
  "Komoda",
  "Krieger",
  "Kuruma",
  "Landstalker",
  "Lynx",
  "Mamba",
  "Manana",
  "Massacro",
  "Mesa",
  "Mesa",
  "Minivan",
  "Minivan заказной",
  "Monroe",
  "Moonbeam",
  "Moonbeam заказной",
  "Mule",
  "Nebula Turbo",
  "Neo",
  "Neon",
  "Nero",
  "Nero заказной",
  "Novak",
  "Omnis",
  "Oracle",
  "Oracle XS",
  "Osiris",
  "Panto",
  "Paragon R",
  "Pariah",
  "Patriot",
  "Patriot Stretch",
  "Penetrator",
  "Penumbra",
  "Peyote",
  "Peyote Gasser",
  "Phoenix",
  "Picador",
  "Pigalle",
  "Prairie",
  "Premier",
  "Primo",
  "Primo заказной",
  "Paradise",
  "Pounder",
  "Radius",
  "Raiden",
  "Rancher XL",
  "Rapid GT",
  "Rapid GT Classic",
  "Rat-Truck",
  "RE-7B",
  "Reaper",
  "Rebel",
  "Rebla GTS",
  "Regina",
  "Retinue",
  "Retinue Mk II",
  "Revolter",
  "Rhapsody",
  "Riata",
  "Rocoto",
  "Roosevelt",
  "Roosevelt Valor",
  "RT3000",
  "Ruiner",
  "Ruston",
  "Rusty Rebel",
  "Rumpo заказной",
  "S80RR",
  "Saber Turbo",
  "Saber Turbo заказной",
  "Sadler",
  "Sandking SWB",
  "Sandking XL",
  "SC1",
  "Schafter",
  "Schafter V12",
  "Schawartzer",
  "Schlagen GT",
  "Seminole",
  "Sentinel",
  "Sentinel Classic",
  "Sentinel XS",
  "Serrano",
  "Seven-70",
  "Slamvan",
  "Slamvan Пропащих",
  "Slamvan заказной",
  "Specter",
  "Specter заказной",
  "Squaddie",
  "Stafford",
  "Stallion",
  "Stanier",
  "Stinger GT",
  "Stirling GT",
  "Stratum",
  "Streiter",
  "Stretch",
  "Stringer",
  "Sugoi",
  "Sultan",
  "Sultan Classic",
  "Sultan RS",
  "Super Diamond",
  "Surano",
  "Surge",
  "Swinger",
  "Seabreeze",
  "Shamal",
  "SuperVolito Carbon",
  "Swift Deluxe",
  "T20",
  "Tailgater",
  "Taipan",
  "Tampa",
  "Tempesta",
  "Tezeract",
  "Thrax",
  "Torero",
  "Tornado",
  "Toros",
  "Tropos Rallye",
  "Tulip",
  "Turismo Classic",
  "Turismo R",
  "Tyrant",
  "Tyrus",
  "V-STR",
  "Vacca",
  "Vagner",
  "Vamos",
  "Verlierer",
  "Vigero",
  "Virgo",
  "Virgo Classic",
  "Virgo Classic заказной",
  "Viseris",
  "Visione",
  "Voltic",
  "Voodoo",
  "Warrener",
  "Washington",
  "Windsor",
  "X80 Proto",
  "XA-21",
  "XLS",
  "Yosemite",
  "Zentorno",
  "Youga",
  "Youga Classic",
  "Youga Classic 4x4",
  "Zion",
  "Zion Cabrio",
  "Zion Classic",
  "Zorrusso"
]
